title: "PPS-24-sgp - ScalaGP"
description: "Report for the PPS-24 project."
remote_theme: just-the-docs/just-the-docs@v0.10.1

# Enable search
search_enabled: true

github:
  private: false
  repository_url: "https://github.com/ItsTiz/PPS-24-sgp"