name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            classifier: linux
          - os: windows-latest
            classifier: win
          - os: macos-latest
            classifier: mac

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Set platform classifier
        run: echo "OS_CLASSIFIER=${{ matrix.classifier }}" >> $GITHUB_ENV

      - name: Build fat JAR
        run: sbt -Denv.classifier=$OS_CLASSIFIER assembly

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: sgp-${{ matrix.classifier }}.jar
          path: sgp-${{ matrix.classifier }}.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Flatten artifact structure
        run: |
          mkdir jars
          find artifacts -name "*.jar" -exec mv {} jars/ \;

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: jars/sgp-*.jar
