name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Build JAR
        run: sbt assembly

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: sgp.jar
